services:
  - type: worker
    name: harveer-wa-bridge
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    disk:
      name: wa-auth
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: wss://cfefhbccvelyuwoqmucu.supabase.co/functions/v1/wa-bridge-ws
        sync: false
      - key: 5149ad5a4351c25aa2b78e354e749d1894b139a603357b9acab5aa9151aed6b8
        sync: false
      - key: 919870761229
        sync: false
